### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by ghost** [ControlEverythingCommunity/SI7050#1]
I have an unrelated project that happens to use the Si7050x IC. My project requires higher reliability and thus validates the checksum byte the sensor returns (see page 13 of the [datasheet](http://www.silabs.com/documents/public/data-sheets/Si7050-1-3-4-5-A20.pdf)). I'd be happy to contribute my implementation, but I'm reluctant to make a pull request until I know what license this project is distributed under; left unspecified it defaults to no license, making any us of the code infinging.

If you want to just go as permissive as possible, you can just use the [WTFPL](http://wtfpl.net/), or the (more professionally worded) [Unlicense](http://unlicense.org/).

**Comment by ghost** [comment]
well, i guess you don't want community contributions after all!

**Comment by zaphod-42** [comment]
Sorry, this whole organization has been growing weeds for the last 2 years with little contribution or activity from the original authors, and I was trying to clean up as much as I could. I added the standard license we use for our official repositories (MIT) and meant to comment to that effect when I closed this ticket. We do appreciate any contributions you have, but as I said the original authors have been pretty inactive, if you are comfortable with the MIT license feel free to make your pull request and I'll check it out as soon as I can (tomorrow).

Thanks!

**Comment by ghost** [comment]
whoops, that's what i get for assuming hostility! sorry about that. MIT sounds fine. i'll see if i can dig up my code and make a PR sometime

**Comment by zaphod-42** [comment]
No worries, like I said I should have commented to explain why I was closing the issue, thanks!
